services:
  discord-bot:
    image: faithchatt/faithchatt-old
    build: .
    restart: always
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /bot
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: Dockerfile
